media: 
  - name: images
    label: Images
    input: src/content/images
    output: src/content/images
    extensions:
      - jpg
      - jpeg
      - png
      - gif
      - svg
      - webp
      - avif
  - name: files
    label: Files
    input: src/content/files
    output: src/content/files

content:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: collection
    format: yaml-frontmatter
    filename: '{slug}.md'
    fields:
      - name: slug
        label: Slug
        type: string
        required: true
        description: The unique identifier for the blog post, used in the URL.
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text # Using 'text' for potentially longer descriptions
        required: true
      - name: author
        label: Author
        type: string
        required: true
      - name: pubDate
        label: Publish Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: updateDate
        label: Last Updated Date
        type: date
        required: false
        options:
          format: yyyy-MM-dd
      - name: mediumLink
        label: Medium Link
        type: string
        required: false
        pattern: # Validates for a URL, matching Zod's .url()
          regex: '^(https?|ftp):\/\/[^\s\/$.?#].[^\s]*$'
          message: 'Please enter a valid URL (e.g., https://example.com/)'
      - name: keywords
        label: Keywords
        type: string
        list: true # Allows multiple keywords, mapping to Zod's z.array(z.string())
        description: A list of keywords for SEO.
      - name: image
        label: Cover Image
        type: image # This aligns with Astro's image helper
        required: true
        description: The main cover image for the blog post.
      - name: body # This represents the main Markdown content after the frontmatter
        label: Content
        type: rich-text # Provides a rich text editor for your Markdown content
        description: The main content of your blog post.
    view:
      fields: [title, author, pubDate, slug]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc

  - name: project
    label: Projects
    path: src/content/projects
    type: collection
    format: yaml-frontmatter
    filename: '{slug}.md'
    fields:
      - name: slug
        label: Slug
        type: string
        required: true
        description: The unique identifier for the project, used in the URL.
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: status
        label: Status
        type: select
        required: true
        options:
          values:
            - In-Progress
            - Active
            - Finished
      - name: updateDate
        label: Last Updated Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: keywords
        label: Keywords
        type: string
        list: true
      - name: technologies
        label: Technologies
        type: string
        list: true
        description: A list of keywords for SEO.
      - name: image
        label: Cover Image
        type: image
        required: false
        description: Optional cover image for the project.
      - name: featured
        label: Featured
        type: boolean
        description: Mark this project as featured on the homepage.
        default: false
      - name: websiteLink
        type: string
        description: URL to the active website
      - name: githubLink
        type: string
        description: URL to the github repository
      - name: demoLink
        type: string
        description: URL to the demo version
      - name: videoLink
        type: string
        description: URL to a video 
      - name: body
        label: Content
        type: rich-text
        description: The main content of your project.
    view:
      fields: [title, status, updateDate, slug]
      primary: title
      sort: [updateDate, title]
      default:
        sort: updateDate
        order: desc