name: Deploy Cloudflare Pages on Source Change

on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**' # Trigger only when files in the 'src' directory change

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloudflare Pages
    environment: main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=smiling-tech-consulting
