name: Deploy Cloudflare Pages on Source Change

on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**' # Trigger only when files in the 'src' directory change

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloudflare Pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build # Runs the build script defined in your package.json

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3 # Uses the official Wrangler GitHub Action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # Your Cloudflare API Token secret
          packageManager: pnpm # Explicitly specifies pnpm as the package manager
          command: pages deploy dist --project-name=smiling-tech-consulting # Deploys the 'dist' folder to your Pages project

    permissions:
      contents: read # Required to checkout the repository
      deployments: write # Required for GitHub Deployments to track your Pages deployments
